TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 250
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.03
  logging_steps: 100 
  evaluation_strategy: "steps"
  eval_steps: 500
  save_steps: 500
  gradient_accumulation_steps: 16
  learning_rate: 5e-5
  load_best_model_at_end: true
  metric_for_best_model: "rouge1"
  greater_is_better: true